services:
  resume_backend:
    image: manzari/resume-backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume_backend
    volumes:
      - ./data:/app/data
    ports:
      - '8081:8080'