services:
  resume_backend_dev:
    image: gradle:jdk17-alpine
    entrypoint: gradle bootRun
    working_dir: /app
    container_name: resume_backend_dev
    volumes:
      - ./:/app
    ports:
      - '8081:8080'
    environment:
      CORS_URL: http://localhost:3000
      DATASOURCE_PASSWORD: secretforest
      DEFAULT_ADMIN_PASSWORD: secretfrog
      LOG_LEVEL: INFO