@auth_token = secret

# Login
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "user1",
  "password": "my-secret"
}
###

# Get Resume
GET http://localhost:8080/resume
Authorization: Bearer {{auth_token}}
###