spring.application.name=resume
spring.datasource.url=jdbc:h2:file:./data/db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=resume
logging.level.org.springframework.security=DEBUG
spring.jpa.hibernate.ddl-auto=update
resume.dataPath=./data/files
spring.datasource.password=secretforest
resume.default-admin-password=secretfrog
resume.default-user-password=RESUME
# must be a base64 representation of resume.default-user-password hashed with SHA2 256bit 64 rounds
resume.default-user-name=0747c96a23dbfa586507337fc4ed4bdddb7b05833243622c4e6bb357b87adb0c