spring.application.name=resume
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.open-in-view = false
spring.datasource.url=jdbc:h2:file:./data/db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=resume
spring.datasource.password=${DATASOURCE_PASSWORD}
logging.level.root=${LOG_LEVEL}
resume.cors-url=${CORS_URL}
resume.api-url=${API_URL}
resume.dataPath=./data/files
resume.default-user-password=RESUME
resume.default-admin-password=${DEFAULT_ADMIN_PASSWORD}
# must be a base64 representation of resume.default-user-password hashed with SHA2 256bit 64 rounds
resume.default-user-name=0747c96a23dbfa586507337fc4ed4bdddb7b05833243622c4e6bb357b87adb0c